//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaturnEdit.Assets.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaturnEdit.Assets.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Editor.
        /// </summary>
        public static string Tabs_ToolTip_ChartEditor {
            get {
                return ResourceManager.GetString("Tabs.ToolTip.ChartEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desc.
        /// </summary>
        public static string Tabs_ToolTip_ChartEditor_Description {
            get {
                return ResourceManager.GetString("Tabs.ToolTip.ChartEditor.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosmetics Editor.
        /// </summary>
        public static string Tabs_ToolTip_CosmeticsEditor {
            get {
                return ResourceManager.GetString("Tabs.ToolTip.CosmeticsEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desc.
        /// </summary>
        public static string Tabs_ToolTip_CosmeticsEditor_Description {
            get {
                return ResourceManager.GetString("Tabs.ToolTip.CosmeticsEditor.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Editor.
        /// </summary>
        public static string Tabs_ToolTip_StageEditor {
            get {
                return ResourceManager.GetString("Tabs.ToolTip.StageEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desc.
        /// </summary>
        public static string Tabs_ToolTip_StageEditor_Description {
            get {
                return ResourceManager.GetString("Tabs.ToolTip.StageEditor.Description", resourceCulture);
            }
        }
    }
}
